;=========================
; Group Solution 3
;
; Members:
; Mikhail Alexi Hatulan
; Arnold Joseph Najera
; Korinne Margaret Sasil
;
;=========================

DATA SEGMENT
    PORTA   EQU 0C8H
    PORTB   EQU 0CAH
    PORTC   EQU 0CCH
    COM_REG EQU 0CEH
DATA ENDS

CODE SEGMENT PUBLIC 'CODE'
ASSUME CS:CODE

START:
    CALL INIT_8255
MAIN_LOOP:
    CALL SELECT_CHANNEL
    CALL LATCH_ADDRESS
    CALL START_CONVERSION
    CALL ENABLE_OUTPUT
    CALL READ_AND_PROCESS
    JMP MAIN_LOOP

INIT_8255 PROC
    MOV DX, COM_REG
    MOV AL, 89H
    OUT DX, AL
    RET
INIT_8255 ENDP

SELECT_CHANNEL PROC
    MOV DX, PORTB
    MOV AL, 00H
    OUT DX, AL
    CALL DELAY_1MS
    RET
SELECT_CHANNEL ENDP

LATCH_ADDRESS PROC
    MOV DX, PORTB
    MOV AL, 08H
    OUT DX, AL
    CALL DELAY_1MS
    RET
LATCH_ADDRESS ENDP

START_CONVERSION PROC
    MOV DX, PORTB
    MOV AL, 88H
    OUT DX, AL
    CALL DELAY_1MS
    CALL DELAY_1MS
    RET
START_CONVERSION ENDP

ENABLE_OUTPUT PROC
    MOV DX, PORTB
    MOV AL, 10H
    OUT DX, AL
    RET
ENABLE_OUTPUT ENDP

READ_AND_PROCESS PROC
    XOR AX, AX
    MOV DX, PORTC
    IN AL, DX
    MOV AH, 0
    MOV BX, 50
    MUL BX
    MOV BX, 255
    DIV BX
    MOV BL, 10
    DIV BL
    MOV CL, 4
    SHL AL, CL
    AND AL, 0F0H
    AND AH, 0FH
    OR AL, AH
    MOV DX, PORTA
    OUT DX, AL
    RET
READ_AND_PROCESS ENDP

DELAY_1MS PROC
    MOV BX, 02CAH
Delay_Loop:
    DEC BX
    NOP
    JNZ Delay_Loop
    RET
DELAY_1MS ENDP

ENDLESS:
    NOP
    JMP ENDLESS

CODE ENDS
END START